### ISSUE TITLE
ConnectionError: timeout on hand shaking

### ISSUE THREAD

**Issue by Finn1510** [namuyan/srudp#2]
Hey, if I am trying to get the demo working.

I get this Error: 
```
Traceback (most recent call last):
  File "C:\Users\flipg\Desktop\sender.py", line 5, in <module>
    sock.connect(("149.224.169.189", 5050))
  File "C:\Users\flipg\AppData\Roaming\Python\Python37\site-packages\srudp\__init__.py", line 190, in connect
    self.bind(tuple(address_copy))
OSError: [WinError 10048] Only one usage of each socket address (protocol/network address/port) is normally permitted
```

I replaced the `<remote host 1,2>` with the Ipv4 adress of each pc.
I want to connect to. Can you tell me what I am doing wrong ?

**Comment by namuyan** [comment]
Hello, port 5050 is already used.

You lack info, you described only one side. How about another?
And please add internet condition, I don’t know you, more and more info will help me to advice.

**Comment by Finn1510** [comment]
OK thanks for the answer =)
I replaced the Port with **6235** and now I am getting this Error : 
```
Traceback (most recent call last):
  File "C:\Users\<User>\Desktop\sender.py", line 5, in <module>
    sock.connect(("<MyIP>", 6235))
  File "C:\Users\<User>\AppData\Roaming\Python\Python37\site-packages\srudp\__init__.py", line 260, in connect
    raise ConnectionError("timeout on hand shaking")
ConnectionError: timeout on hand shaking 
```

On computer A, I have the "sender" demo script and on computer B the "receive" demo script you provided in the Readme.md. I replaced the `<remote host 1>` on computer A with the Ip adress from Computer B and the `<remote host 2>` on computer B with the Ip adress of Computer A .
Computer A and B are on the same network, btw.

**Comment by namuyan** [comment]
Port binding problem was solved, great❕

Next, you failed to punch a hole.
* Check network security policy about UDP
* You looks using old source, please install from github source
* Explore about UDP hole punching
* same network? What do you mean? LAN?

You may be doing something wrong. It's rarely disturbed by anything other than network security policy. I find public wifi and  school network restrict UDP and TCP connection.
I would like you to talk to someone familiar with your network and write down all relevant information as much as possible.

**Comment by Finn1510** [comment]
Hey thanks again for the very quick answer !

Yes the two computers are in the same wifi network (for testing purposes).

I installed Scrupd via Pip a few days ago... is an old source or is the newest version only on Github ? 

I'll check my security policy soon ^^

**Comment by Finn1510** [comment]
I checked my network security policy regarding UDP and I found nothing special... 
Is there anything else I can do to get this working ? I really want to use srudp

**Comment by namuyan** [comment]
Good network condition!
But really? please confirm by UDP socket connection setup on two sides.

And, did you finish above lists? and heard about below?
> I would like you to talk to someone familiar with your network and write down all relevant information as much as possible.

I’m not you (just repo owner) and only just be given info and advice, I can’t try & error beside you often.
